baseURL = 'https://lasermetal.art/'
languageCode = 'en-us'
title = 'Laser Metal Art'

[params]
    mapIframe = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.5766407045967!2d-0.0139705!3d51.5209826!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761d4e655c823d%3A0xc91cff08002c695a!2s201%2C%2030%20Brickfield%20Rd%2C%20London%20E3%203LT%2C%20UK!5e0!3m2!1sen!2str!4v1669547582531!5m2!1sen!2str"
    footerText = "Studio 201 30 Brickfield Road London E3 3LT"
    address = "Studio 201 30 Brickfield Road London E3 3LT"
    instagram = "lasermetal.art"
    email = "studio@starholden.com"
    formUrl = "https://getform.io/f/6385fe99-794b-47ba-9ae3-c067ebb80979"

[menu]
    [[menu.header]]
        identifier = 'home'
        name = 'Metal Art'
        url = '/'
        weight = 1
    [[menu.header]]
        identifier = 'gallery'
        name = 'gallery'
        url = '/gallery'
        weight = 10
    [[menu.header]]
        identifier = 'about'
        name = 'about'
        url = '#'
        weight = 20
    [[menu.header]]
        identifier = 'the-process'
        parent = 'about'
        name = 'The Process'
        url = '/about/the-process'
        weight = 10
    [[menu.header]]
        identifier = 'family-business'
        parent = 'about'
        name = 'Family Business'
        url = '/about/family-business'
        weight = 20
    [[menu.header]]
        identifier = 'faq'
        parent = 'about'
        name = 'F.A.Q'
        url = '/about/faq'
        weight = 30
    [[menu.header]]
        identifier = 'contact'
        parent = 'about'
        name = 'Contact'
        url = '/about/contact'
        weight = 40
